#Dev enviroment

app:
  message: This is property file fo the ${string.application.name} specific for Dev enviroment

spring:
  datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
   username: sa
   password: sa